version: "3.7"
services:
  # docker-host:
  #   image: qoomon/docker-host
  #   cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
  #   restart: on-failure
  #   environment:
  #     - PORTS=80
  #   networks:
  #     - bridge_service

  bridge-service:
    build: .
    env_file:
      - "./.env"
    ports:
      - 8085:8085
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bridge_service
    depends_on:
      - psql
    #   - docker-host

  psql:
    image: postgres:13-alpine
    ports:
        - 5433:5432
    volumes:
        - "./postgres_data:/var/lib/postgresql/data"
    networks:
        - bridge_service
    environment:
      POSTGRES_DB: "final-project"
      POSTGRES_USER: "final-project"
      POSTGRES_PASSWORD: "final-project"
      PGDATA: "/var/lib/postgresql/data/pgdata"

networks:
  bridge_service:
    driver: bridge
    name: bridge_service
